// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAju8iao2jULA5kWXnQta7unsqCnoQPtE8',
    appId: '1:271409583512:android:848af81e83e335413047ed',
    messagingSenderId: '271409583512',
    projectId: 'fir-pplg2-67b38',
    storageBucket: 'fir-pplg2-67b38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcfCT5rnaSMt34MPA0tYHpoq2mdqtfoYw',
    appId: '1:271409583512:ios:aa883b3d8baf24923047ed',
    messagingSenderId: '271409583512',
    projectId: 'fir-pplg2-67b38',
    storageBucket: 'fir-pplg2-67b38.firebasestorage.app',
    androidClientId: '271409583512-nh3il0qcjp9j14d72bnno4rbmeupbc17.apps.googleusercontent.com',
    iosClientId: '271409583512-eqs5lrgobp5rj3gag75bmt1v31qjbk8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveNotes',
  );
}
